---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  json_web_token_secret: <%= ENV['SECRET_TOKEN'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
